# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: vite-vue-ts
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        if: ${{ steps.release.outputs.release_created }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm install
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm run build
        if: ${{ steps.release.outputs.release_created }}
      - run: echo "v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
        if: ${{ steps.release.outputs.release_created }}
      - run: echo "成功了！"
        if: ${{ steps.release.outputs.release_created && success() }}
      - run: echo "失敗了！"
        if: ${{ steps.release.outputs.release_created && failure() }}
