# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get package version
        id: get-version
        run: |
          npm pkg get version
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - run: |
          echo "Package version: ${{ steps.get-version.outputs.current_version }}"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install & pnpm run build
